---
.in-rust-environment:
  image: rust:slim-buster
  before_script:
    - rustc --version
    - cargo --version
    - rustup --version
    - rustup component add llvm-tools-preview
  tags:
    - docker

.rust-build:
  extends:
    - .in-rust-environment
  script: |
    cargo build --release --verbose
  interruptible: true

# yamllint disable rule:line-length
.rust-test:
  image: rustlang/rust:nightly-slim
  extends:
    - .in-rust-environment
  script: |
    apt-get update -qq && apt-get install -y -qq lcov --no-install-recommends
    cargo install --color=always --force grcov
    cargo test --workspace --verbose
    grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing --ignore "/*" -o coverage.info
    lcov -l coverage.info
  coverage: '/Total:\|\s*(\d+\.\d+)%/'
  interruptible: true
  variables:
    RUSTFLAGS: '-Zinstrument-coverage'
# yamllint enable rule:line-length
